# Generated by Django 4.1.7 on 2023-03-28 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='apelido',
            new_name='apellido',
        ),
    ]
