# Generated by Django 4.1.7 on 2023-03-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_rename_apelido_clientes_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='marca',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='modelo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='apellido',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
